###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: efair-gilead-mysql
      working_dir: /application
      restart: unless-stopped
      tty: true
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD={a%43[6UZdddC[]
        - MYSQL_DATABASE=efair-gilead-db
        - MYSQL_USER=admin
        - MYSQL_PASSWORD={a%43[6UZdddC[]
      ports:
        - "3306:3306"

    webserver:
      image: nginx:alpine
      container_name: efair-gilead-webserver
      working_dir: /application
      restart: unless-stopped
      tty: true
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "80:80"
        - "443:443"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: onlinevm-php-fpm
      restart: unless-stopped
      tty: true
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
